export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const SET_ITEM_SELECTED = "SET_ITEM_SELECTED";
export const SELECT_BUDGET_ITEM = "SELECT_BUDGET_ITEM";
export const DESELECT_BUDGET_ITEM = "DESELECT_BUDGET_ITEM";
export const SELECT_PRICE = "SELECT_PRICE";
export const DESELECT_PRICE = "DESELECT_PRICE";
export const ADD_RECORD = "ADD_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";
export const DELETE_ALL_RECORD = "DELETE_ALL_RECORD";
export const ACTIVITY_FINISHED = "ACTIVITY_FINISHED";
export const ACTIVITY_STARTED = "ACTIVITY_STARTED";

// Forge Requests
export const SET_FORGE_ACCESS = "SET_FORGE_ACCESS";
export const SET_VIEWER_ACCESS = "SET_VIEWER_ACCESS";
export const GET_BUCKETS = "GET_BUCKETS";
export const GET_MODELS = "GET_MODELS";
export const POST_LOADING = "POST_LOADING";
export const MANAGEMENT_LOADING = "MANAGEMENT_LOADING";
export const CONVERT_MODEL = "CONVERT_MODEL";
export const GET_OBJECT_INFO = "GET_OBJECT_INFO";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_WORKITEMS = "GET_WORKITEMS";
export const GET_MODEL_INFO = "GET_MODEL_INFO";
